# **Numpy Introduction**

In [1]:
# install the library
!pip install numpy 

In [2]:
# import the library
import numpy as np

## What is an Array?

An **array** is a collection of items stored at continuous memory locations.  
In Python, we mostly use **NumPy arrays** instead of lists when working with numbers, because they are:

1. **Fast** – NumPy arrays are optimized for numerical operations.  
2. **Efficient** – They use less memory compared to Python lists.  
3. **Convenient** – Many built-in functions make calculations easy.  

### Key Points:
- An array can store multiple values in one variable.  
- All elements in a NumPy array must be of the **same data type**.  
- Arrays can be **1D, 2D, or multi-dimensional**.  

### Example:


In [3]:
# Simple NumPy Examples
import numpy as np  

# 1D Array  
arr1 = np.array([1, 2, 3, 4])  

# 2D Array  
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  

print("1D Array:", arr1)
print("2D Array:", arr2)


1D Array: [1 2 3 4]
2D Array: [[1 2 3]
 [4 5 6]]


In [4]:
# simple 1D array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
# simple 2D array
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


> **1D Array**: have only one bracket it contain only columns

> **2D Array**: have two brackets it contain both row and columns

In [6]:
# another way to create 2D array
a3 = np.arange(6).reshape(2, 3)
print(a3)

[[0 1 2]
 [3 4 5]]


In [7]:
# check the shape of arrays
print("Shape of a:", a.shape)
print("Shape of a2:", a2.shape)
print("Shape of a3:", a3.shape)

Shape of a: (6,)
Shape of a2: (1, 6)
Shape of a3: (2, 3)


> #### Shapes
>- shape of a: it shows `a` have only 6 columns
>- shape of a2: it shows `a2` have 1 rows and 6 columns
>- shape of a3: it shows `a3` have 2 rows and 3 columns

### 3D Array
- it is mostly use in image analysis

In [8]:
# 3D array
a4 = a2[np.newaxis, :]
print(a4)

# check the shape of array
a4.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

In [35]:
# we can check the data type of arrays
print(a4.dtype)

# we can also check check the type of data
type(a4)

int64


numpy.ndarray

## Why do we have 1D, 2D, and 3D Arrays?

Arrays come in different dimensions because data in real life is not always stored in a simple line.  
Depending on the type of data, we use different dimensional arrays.

### 1D Array
- Looks like a simple list of numbers.  
- Example: `[10, 20, 30, 40]`  
- **Use in Data Science:** To store features like a single column (e.g., ages of people).  

### 2D Array
- Data stored in rows and columns (like a table).  
- Example:\
           [[1, 2, 3],\
             [4, 5, 6]]

- **Use in Data Science:** To store datasets in tabular form (e.g., rows = students, columns = marks).  

### 3D Array
- Collection of 2D arrays stacked together (like pages in a book).  
- Example: multiple tables of data.  
- **Use in Data Science:** To work with images (height × width × color channels) or time series with multiple features.  

### Summary
- **1D:** For single feature data.  
- **2D:** For tabular data.  
- **3D:** For complex data like images, videos, or multi-dimensional signals.  

---

# Creating Arrays With Numpy

In [12]:
# simple array
a = np.array([1, 2, 3, 4, 5])
b = np.array([(1, 2, 3, 4, 5),(6, 7, 8, 9, 0)])
print("1D Array: ", a)
print("2D Array: " ,b)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3 4 5]
 [6 7 8 9 0]]


In [13]:
# check the shape of a
a.shape


(5,)

> there is only 5 columns

In [14]:
# shape of b array
b.shape

(2, 5)

> there is 2 rows and 5 columns

# Initilize Arrays

In [42]:
# array fill with zeros
zeros = np.zeros((3,4))   # 3 rows and 4 columns
# check the data type of array
print(zeros.dtype)
# check the data type
print(type(zeros))
zeros

float64
<class 'numpy.ndarray'>


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
# array of ones
ones = np.ones((2,5))   # (rows, columns)
# check the data type of array
print(ones.dtype)
# check the type of data
print(type(ones))
ones

float64
<class 'numpy.ndarray'>


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# full array
full = np.full((3,5), 5)   # ((rows, columns), filling value)
# check the data type
print(full.dtype)
# check the type of data
print(type(full))
full

int64
<class 'numpy.ndarray'>


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## Identity Matrix

An **Identity Matrix** is a special square matrix in which:  
- All the elements on the **main diagonal** are `1`.  
- All the other elements are `0`.  

### Example (3×3 Identity Matrix):
1 0 0\
0 1 0\
0 0 1

In [43]:
# creating identity matrix
identity = np.eye(5)   # 5×5 Identity Matrix
# check the data type of array
print(identity.dtype)
# check the type of data
print(type(identity))
identity

float64
<class 'numpy.ndarray'>


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Attributes of Array

In [48]:
# array
a = np.array([1, 2, 3, 4, 5])
b = np.array([(1, 2, 3, 4, 5),(6, 7, 8, 9, 0)])

In [44]:
# check the shpe
b.shape

(2, 5)

In [54]:
# check the Lenght of array
len(a)

5

In [52]:
# check the Number Elements in array
b.size

10

In [53]:
# check the Dimention of array
b.ndim

2

# Basic Oprations of Array

In [55]:
# array
a = np.array([1, 2, 3, 4, 5])
b = np.array([(1, 2, 3, 4, 5),(6, 7, 8, 9, 0)])

In [ ]:
# subtraction
g = a-b
g

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5,  5]])

In [ ]:
# addition
g = a + b
g

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13,  5]])

In [63]:
# another way of addition
g1 = np.add(a, b)
g1

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13,  5]])

In [59]:
# multiplication
g = a * b
g

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36,  0]])

In [ ]:
# devision
g = a / b
g

/tmp/ipykernel_6814/3263949806.py:2: RuntimeWarning: divide by zero encountered in divide
  g = a / b


array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     , 0.44444444,        inf]])

In [64]:
# squre of each element
s = a ** 2
s

array([ 1,  4,  9, 16, 25])