# Numpy idexing and slicing

In [1]:
import numpy as np

In [3]:
# create an array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# disply the only first item of array
a[0]

np.int64(1)

In [5]:
# featch the first element to onward
a[0:]

array([1, 2, 3, 4, 5, 6])

In [8]:
# create an array
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# reshape the b array and convert into 2D array
c = b.reshape(2, 3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [12]:
# indixing on 2D array
c[0]

array([0, 2, 4])

In [13]:
c[1]

array([ 6,  8, 10])

In [15]:
# indexing on first row
c[0,2]

np.int64(4)

In [18]:
# we can perform any condition on array
# Example
c[(c < 5) & (c > 3)]

array([4])