# Creating matrices

In [1]:
# create a 2 by 3 matrix
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
# create a matrix of big dimension
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [3]:
# slicing a matrix
c = b[0:5, 1:3]          # row 0 to 4 and column 1 to 2
c

array([[ 2,  4],
       [22, 24],
       [42, 44],
       [62, 64],
       [82, 84]])

In [4]:
# find the max of b
print("the max of b is",b.max())
# find the min of b
print("the min of b is",b.min())
# find the sum of b
print("the sum of b is",b.sum())
# find the mean of b
print("the mean of b is",b.mean())
# find the standard deviation of b
print("the standard deviation of b is",b.std())

the max of b is 98
the min of b is 0
the sum of b is 2450
the mean of b is 49.0
the standard deviation of b is 28.861739379323623


> axis-0 = columns wise\
> axis-1 = row wise

In [5]:
# find the max at 0 axis
print("the max at 0 axis is",b.max(axis=0))
# find the max at 1 axis
print("the max at 1 axis is",b.max(axis=1))

the max at 0 axis is [80 82 84 86 88 90 92 94 96 98]
the max at 1 axis is [18 38 58 78 98]


In [6]:
# find the min at 0 axis
print("the min at 0 axis is",b.min(axis=0))
# find the min at 1 axis
print("the min at 1 axis is",b.min(axis=1))

the min at 0 axis is [ 0  2  4  6  8 10 12 14 16 18]
the min at 1 axis is [ 0 20 40 60 80]


In [7]:
# find the sum at 0 axis
print("the sum at 0 axis is",b.sum(axis=0))
# find the sum at 1 axis
print("the sum at 1 axis is",b.sum(axis=1))

the sum at 0 axis is [200 210 220 230 240 250 260 270 280 290]
the sum at 1 axis is [ 90 290 490 690 890]


In [8]:
# find the std  at 0 axis
print("the std at 0 axis is",b.std(axis=0))
# find the std at 1 axis
print("the std at 1 axis is",b.std(axis=1))

the std at 0 axis is [28.28427125 28.28427125 28.28427125 28.28427125 28.28427125 28.28427125
 28.28427125 28.28427125 28.28427125 28.28427125]
the std at 1 axis is [5.74456265 5.74456265 5.74456265 5.74456265 5.74456265]


In [9]:
# find the mean at 0 axis
print("the mean at 0 axis is",b.mean(axis=0))
# find the mean at 1 axis
print("the mean at 1 axis is",b.mean(axis=1))

the mean at 0 axis is [40. 42. 44. 46. 48. 50. 52. 54. 56. 58.]
the mean at 1 axis is [ 9. 29. 49. 69. 89.]


In [10]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [12]:
# create matrix
m = np.arange(0, 20, 2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
# add the values in all rows
m + np.array([20, 22])      # instead of addition we perform any mathmatical opration

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [19]:
# add the complete row at botum
np.vstack((m,+ np.array([20, 22])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [16]:
# find the unique items
np.unique(m)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# reverse the array
np.flip(m)

array([[18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4],
       [ 2,  0]])